[cerebrium.deployment]
name = "outbound-livekit-agent"
python_version = "3.11"
docker_base_image_url = ""
disable_auth = false
include = ['main.py', 'cerebrium.toml', 'requirements.txt', 'Dockerfile', '.env', 'voice_pipeline_agent.py', 'outbound-trunk.json', 'required_data.txt', 'test.py']
# exclude = ['venv', '__pycache__', '.*']

[cerebrium.hardware]
cpu = 2
memory = 8.0
compute = "CPU"

[cerebrium.scaling]
min_replicas = 1
max_replicas = 5
cooldown = 30
replica_concurrency = 1


[cerebrium.dependencies.paths]
pip = "requirements.txt"

[cerebrium.runtime.custom]
port = 8081
dockerfile_path = "./Dockerfile"